version: '3'
services:
  backend:
    container_name: toohak
    ports:
      - "3000:3000"
      - "3080:3080"
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - toohak_db:/app/backend/db/
volumes:
  toohak_db:
